### ISSUE TITLE
bug较多~

### ISSUE THREAD

**Issue by NewFuture** [xinyu3ru/renren-bak#1]
刚好今天清人人，发现这个居然今天还在更新，太神奇了 😃 

然鹅，问题比较多:
 * cls 清屏(linux clear)
 * 密码明文
 * 解码方式太原始粗暴了 😂 (导致解析BUG)
 * blog的失效图片链接网络异常，会直接崩溃
 

虽然代码有点儿惨不忍睹，改改还能用 😹 

thanks for your good job~

**Comment by xinyu3ru** [comment]
那段时间写着玩用的，至今水平也没有长进，今天更新只是顺手更了一下图片链接。
谢谢您的完善和修正。

**Comment by NewFuture** [comment]
哈哈，很实用 ✌️
