### ISSUE TITLE
输入验证码，输入账号密码后报错

### ISSUE THREAD

**Issue by shixuguo** [xinyu3ru/renren-bak#3]
报错信息如下：
```
Traceback (most recent call last):
  File "Renren.py", line 1005, in <module>
    main()
  File "Renren.py", line 852, in main
    u_id = ren.login()
  File "Renren.py", line 62, in login
    symbol_code_num = symbol_code.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

这一段代码逻辑大概是什么？

我知道你可能没有时间继续维护这个项目，
我自己也有Python爬虫开发的经验，
如果你可以给我提供一些指导，我可以继续维护这个项目

**Comment by xinyu3ru** [comment]
main()是常规的主程序入口
ren.login()是登录程序的入口

`            try_login = self.post_data(self.login_url, self.params)
            is_success = re.search('ren\.com/\d+', try_login.url)
            if not is_success:
                symbol_code = self.get_symbol_code.search(try_login.url)
                symbol_code_num = symbol_code.group(1)
                if symbol_code_num == '512':
                    self.i_get_img()
                    img_content = input('打开文件夹查看并输入验证码：')
                    self.params['icode'] = img_content
                    continue
                clear()
                print(config.FAILCODE[symbol_code_num])
            else:
                user_page = try_login.url
                # print(user_page)
                self.is_login = 1
                user_id = self.get_user_id(user_page)`
![image](https://user-images.githubusercontent.com/3859309/35465614-347215e2-0338-11e8-85fd-2ebc9169cbee.png)

问题中 File "Renren.py", line 62, in login
    symbol_code_num = symbol_code.group(1)

第62行运行中出现问题
上述代码中
首先向人人网发一个登录账号密码的post请求，根据返回的网址try_login.url，  re筛选出来是否有登录成功标志（ren\.com/\d+），如果有就置1（is_success），没有就进入输入验证码的环节（ if not is_success:）
通过返回的网址的相关错误代码（ symbol_code ），如果是512就是需用输入验证码，其他的数字就需用进行其他的处理，后面代码就是下载验证码图片 人工查看图片，输入验证码，最后在重试尝试登录一次

时间比较久了，相关验证或者验证码的错误代码可能会更新掉了，这地方登录不进去也是挺正常的

甚至登录模式都改变了

关于维护，个人用完了代码，其他网友对人人网需求的也不算很多，就没有继续维护，需用的话可以pull回来或者自己建一个分支继续维护就可以了

**Comment by shixuguo** [comment]
我对git 的pull还不是很懂，但这个不是主要问题。

我想了解一下，你之前下载一个人的日志照片加起来大概要多长时间？

**Comment by xinyu3ru** [comment]
一般几分钟就够了，最多十多分钟
一个人的数据也没有多少
照片也不是原图，都是缩放过的图

**Comment by xinyu3ru** [comment]
bitdust同学更新了一下代码，他回复说正常使用了
